/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author danie
 */
public class MenuUsuario extends javax.swing.JFrame {

    /**
     * Creates new form MenuUsuario
     */
    public MenuUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPerfil = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnReservar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtBienvenida = new javax.swing.JLabel();
        imagen3 = new javax.swing.JLabel();
        imagen1 = new javax.swing.JLabel();
        imagen2 = new javax.swing.JLabel();
        nombreObra3 = new javax.swing.JLabel();
        nombreObra1 = new javax.swing.JLabel();
        nombreObra2 = new javax.swing.JLabel();
        descripcion3 = new javax.swing.JLabel();
        descripcion1 = new javax.swing.JLabel();
        descripcion2 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(28, 12, 91));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPerfil.setBackground(new java.awt.Color(28, 12, 91));
        btnPerfil.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setText("Perfil");
        btnPerfil.setBorder(null);
        btnPerfil.setBorderPainted(false);
        btnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfil.setFocusPainted(false);
        jPanel2.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 110, 60));

        btnInicio.setBackground(new java.awt.Color(28, 12, 91));
        btnInicio.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Inicio");
        btnInicio.setBorder(null);
        btnInicio.setBorderPainted(false);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setFocusPainted(false);
        jPanel2.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, 60));

        btnReservar.setBackground(new java.awt.Color(28, 12, 91));
        btnReservar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnReservar.setForeground(new java.awt.Color(255, 255, 255));
        btnReservar.setText("Reservar");
        btnReservar.setBorder(null);
        btnReservar.setBorderPainted(false);
        btnReservar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReservar.setFocusPainted(false);
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });
        jPanel2.add(btnReservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 120, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 80));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBienvenida.setBackground(new java.awt.Color(255, 255, 255));
        txtBienvenida.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        txtBienvenida.setForeground(new java.awt.Color(0, 124, 186));
        txtBienvenida.setText("Bienvenido @NombreUsuario");
        jPanel3.add(txtBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        imagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portada.jpg"))); // NOI18N
        jPanel3.add(imagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 150, 150));

        imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portada.jpg"))); // NOI18N
        jPanel3.add(imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 150, 150));

        imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portada.jpg"))); // NOI18N
        jPanel3.add(imagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 150, 150));

        nombreObra3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        nombreObra3.setForeground(new java.awt.Color(0, 124, 186));
        nombreObra3.setText("Nombre Obra 3");
        nombreObra3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(nombreObra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 120, -1));

        nombreObra1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        nombreObra1.setForeground(new java.awt.Color(0, 124, 186));
        nombreObra1.setText("Nombre Obra 1");
        jPanel3.add(nombreObra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        nombreObra2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        nombreObra2.setForeground(new java.awt.Color(0, 124, 186));
        nombreObra2.setText("Nombre Obra 2");
        jPanel3.add(nombreObra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        descripcion3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        descripcion3.setForeground(new java.awt.Color(102, 102, 102));
        descripcion3.setText("Descripción");
        jPanel3.add(descripcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));

        descripcion1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        descripcion1.setForeground(new java.awt.Color(102, 102, 102));
        descripcion1.setText("Descripción");
        jPanel3.add(descripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        descripcion2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        descripcion2.setForeground(new java.awt.Color(102, 102, 102));
        descripcion2.setText("Descripción");
        jPanel3.add(descripcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        btnCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(0, 124, 186));
        btnCerrarSesion.setText("Cerrar sesión ");
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setFocusPainted(false);
        jPanel3.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 150, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 700, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUsuario().setVisible(true);
            }
        });
    }

    public JButton getBtnCerrarSesion() {
        return btnCerrarSesion;
    }

    public JButton getBtnInicio() {
        return btnInicio;
    }

    public JButton getBtnPerfil() {
        return btnPerfil;
    }

    public JButton getBtnReservar() {
        return btnReservar;
    }
    
    

    public JLabel getDescripcion1() {
        return descripcion1;
    }

    public void setDescripcion1(JLabel descripcion1) {
        this.descripcion1 = descripcion1;
    }

    public JLabel getDescripcion2() {
        return descripcion2;
    }

    public void setDescripcion2(JLabel descripcion2) {
        this.descripcion2 = descripcion2;
    }

    public JLabel getDescripcion3() {
        return descripcion3;
    }

    public void setDescripcion3(JLabel descripcion3) {
        this.descripcion3 = descripcion3;
    }

    public JLabel getImagen1() {
        return imagen1;
    }

    public void setImagen1(JLabel imagen1) {
        this.imagen1 = imagen1;
    }

    public JLabel getImagen2() {
        return imagen2;
    }

    public void setImagen2(JLabel imagen2) {
        this.imagen2 = imagen2;
    }

    public JLabel getImagen3() {
        return imagen3;
    }

    public void setImagen3(JLabel imagen3) {
        this.imagen3 = imagen3;
    }

    public JLabel getNombreObra1() {
        return nombreObra1;
    }

    public void setNombreObra1(JLabel nombreObra1) {
        this.nombreObra1 = nombreObra1;
    }

    public JLabel getNombreObra2() {
        return nombreObra2;
    }

    public void setNombreObra2(JLabel nombreObra2) {
        this.nombreObra2 = nombreObra2;
    }

    public JLabel getNombreObra3() {
        return nombreObra3;
    }

    public void setNombreObra3(JLabel nombreObra3) {
        this.nombreObra3 = nombreObra3;
    }

    public JLabel getTxtBienvenida() {
        return txtBienvenida;
    }

    public void setTxtBienvenida(JLabel txtBienvenida) {
        this.txtBienvenida = txtBienvenida;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnReservar;
    private javax.swing.JLabel descripcion1;
    private javax.swing.JLabel descripcion2;
    private javax.swing.JLabel descripcion3;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel imagen2;
    private javax.swing.JLabel imagen3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nombreObra1;
    private javax.swing.JLabel nombreObra2;
    private javax.swing.JLabel nombreObra3;
    private javax.swing.JLabel txtBienvenida;
    // End of variables declaration//GEN-END:variables
}
