/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author danie
 */
public class RegistroUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form RegistroUsuarios
     */
    public RegistroUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        entradaContrasena = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        entradaNombre = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        entradaApellido = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        entradaCurp = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        entradaUsuario = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        entradaConfirmacionContrasena = new javax.swing.JPasswordField();
        btnRegistro = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        textError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setMinimumSize(new java.awt.Dimension(400, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(28, 12, 91));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de Usuarios");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 250, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 124, 186));
        jLabel2.setText("<html> Confirmar contraseña: </html>");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 140, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 124, 186));
        jLabel3.setText("Usuario:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        jLabel3.getAccessibleContext().setAccessibleDescription("Nombre de Usuario");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 124, 186));
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 124, 186));
        jLabel5.setText("Apellido:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 124, 186));
        jLabel6.setText("CURP:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 124, 186));
        jLabel7.setText("Contraseña:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jPanel3.setBackground(new java.awt.Color(187, 187, 187));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entradaContrasena.setBackground(new java.awt.Color(187, 187, 187));
        entradaContrasena.setBorder(null);
        jPanel3.add(entradaContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 260, 20));

        jPanel4.setBackground(new java.awt.Color(187, 187, 187));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entradaNombre.setBackground(new java.awt.Color(187, 187, 187));
        entradaNombre.setToolTipText("Nombre de pila");
        entradaNombre.setBorder(null);
        jPanel4.add(entradaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 280, -1));

        jPanel5.setBackground(new java.awt.Color(187, 187, 187));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entradaApellido.setBackground(new java.awt.Color(187, 187, 187));
        entradaApellido.setToolTipText("Apellido");
        entradaApellido.setBorder(null);
        jPanel5.add(entradaApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 20));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 280, -1));

        jPanel6.setBackground(new java.awt.Color(187, 187, 187));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entradaCurp.setBackground(new java.awt.Color(187, 187, 187));
        entradaCurp.setToolTipText("CURP");
        entradaCurp.setBorder(null);
        jPanel6.add(entradaCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 20));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 280, -1));

        jPanel7.setBackground(new java.awt.Color(187, 187, 187));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entradaUsuario.setBackground(new java.awt.Color(187, 187, 187));
        entradaUsuario.setToolTipText("Nombre de Usuario");
        entradaUsuario.setBorder(null);
        jPanel7.add(entradaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 20));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 280, 20));

        jPanel8.setBackground(new java.awt.Color(187, 187, 187));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entradaConfirmacionContrasena.setBackground(new java.awt.Color(187, 187, 187));
        entradaConfirmacionContrasena.setBorder(null);
        jPanel8.add(entradaConfirmacionContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 20));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 190, -1));

        btnRegistro.setBackground(new java.awt.Color(0, 124, 186));
        btnRegistro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistro.setText("Registrarse");
        btnRegistro.setBorderPainted(false);
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistro.setDefaultCapable(false);
        btnRegistro.setFocusPainted(false);
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, 30));

        btnAtras.setBackground(new java.awt.Color(255, 255, 255));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(0, 124, 186));
        btnAtras.setText("Atrás");
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.setFocusPainted(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 80, 30));

        textError.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textError.setForeground(new java.awt.Color(255, 0, 0));
        textError.setText("Error");
        jPanel1.add(textError, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuarios().setVisible(true);
            }
        });
    }

    public JButton getBtnAtras() {
        return btnAtras;
    }

    public JButton getBtnRegistro() {
        return btnRegistro;
    }

    public JTextField getEntradaApellido() {
        return entradaApellido;
    }

    public JPasswordField getEntradaConfirmacionContrasena() {
        return entradaConfirmacionContrasena;
    }

    public JPasswordField getEntradaContrasena() {
        return entradaContrasena;
    }

    public JTextField getEntradaCurp() {
        return entradaCurp;
    }

    public JTextField getEntradaNombre() {
        return entradaNombre;
    }

    public JTextField getEntradaUsuario() {
        return entradaUsuario;
    }

    public JLabel getTextError() {
        return textError;
    }

    public void setTextError(JLabel textError) {
        this.textError = textError;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JTextField entradaApellido;
    private javax.swing.JPasswordField entradaConfirmacionContrasena;
    private javax.swing.JPasswordField entradaContrasena;
    private javax.swing.JTextField entradaCurp;
    private javax.swing.JTextField entradaNombre;
    private javax.swing.JTextField entradaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel textError;
    // End of variables declaration//GEN-END:variables
}
