package vista;

import javax.swing.JButton;

public class VistaObra extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    public VistaObra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnVolverAtras = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnCrearObra = new javax.swing.JButton();
        btnModificarObra = new javax.swing.JButton();
        btnEliminarObra = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnFunciones = new javax.swing.JButton();
        btnObras = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Control Obras");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(700, 400));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 400));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolverAtras.setBackground(new java.awt.Color(255, 255, 255));
        btnVolverAtras.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVolverAtras.setForeground(new java.awt.Color(0, 124, 186));
        btnVolverAtras.setText("Volver atrás");
        btnVolverAtras.setBorderPainted(false);
        btnVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverAtrasActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 150, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 124, 186));
        jLabel3.setText("¿Qué acción deseas realizar?");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        btnCrearObra.setBackground(new java.awt.Color(28, 12, 91));
        btnCrearObra.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCrearObra.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearObra.setText("Crear obra");
        btnCrearObra.setBorderPainted(false);
        btnCrearObra.setDefaultCapable(false);
        btnCrearObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearObraActionPerformed(evt);
            }
        });
        jPanel2.add(btnCrearObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 190, 80));

        btnModificarObra.setBackground(new java.awt.Color(28, 12, 91));
        btnModificarObra.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnModificarObra.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarObra.setText("Modificar obra");
        btnModificarObra.setBorderPainted(false);
        btnModificarObra.setDefaultCapable(false);
        jPanel2.add(btnModificarObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 190, 80));

        btnEliminarObra.setBackground(new java.awt.Color(28, 12, 91));
        btnEliminarObra.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEliminarObra.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarObra.setText("Eliminar obra");
        btnEliminarObra.setBorderPainted(false);
        btnEliminarObra.setDefaultCapable(false);
        btnEliminarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarObraActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 180, 80));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 700, 420));

        jPanel4.setBackground(new java.awt.Color(28, 12, 91));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFunciones.setBackground(new java.awt.Color(28, 12, 91));
        btnFunciones.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnFunciones.setForeground(new java.awt.Color(255, 255, 255));
        btnFunciones.setText("Funciones");
        btnFunciones.setBorder(null);
        btnFunciones.setBorderPainted(false);
        btnFunciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFunciones.setDefaultCapable(false);
        btnFunciones.setFocusPainted(false);
        jPanel4.add(btnFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 110, 60));

        btnObras.setBackground(new java.awt.Color(28, 12, 91));
        btnObras.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnObras.setForeground(new java.awt.Color(255, 255, 255));
        btnObras.setText("Obras");
        btnObras.setBorder(null);
        btnObras.setBorderPainted(false);
        btnObras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnObras.setDefaultCapable(false);
        btnObras.setFocusPainted(false);
        jPanel4.add(btnObras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, 60));

        btnUsuarios.setBackground(new java.awt.Color(28, 12, 91));
        btnUsuarios.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setBorder(null);
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.setDefaultCapable(false);
        btnUsuarios.setFocusPainted(false);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jPanel4.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 120, 60));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 80));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverAtrasActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnEliminarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarObraActionPerformed

    private void btnCrearObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearObraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaObra().setVisible(true);
            }
        });
    }

    public JButton getBtnCrearObra() {
        return btnCrearObra;
    }

    public void setBtnCrearObra(JButton btnCrearObra) {
        this.btnCrearObra = btnCrearObra;
    }

    public JButton getBtnEliminarObra() {
        return btnEliminarObra;
    }

    public void setBtnEliminarObra(JButton btnEliminarObra) {
        this.btnEliminarObra = btnEliminarObra;
    }

    public JButton getBtnFunciones() {
        return btnFunciones;
    }

    public void setBtnFunciones(JButton btnFunciones) {
        this.btnFunciones = btnFunciones;
    }

    public JButton getBtnModificarObra() {
        return btnModificarObra;
    }

    public void setBtnModificarObra(JButton btnModificarObra) {
        this.btnModificarObra = btnModificarObra;
    }

    public JButton getBtnObras() {
        return btnObras;
    }

    public void setBtnObras(JButton btnObras) {
        this.btnObras = btnObras;
    }

    public JButton getBtnUsuarios() {
        return btnUsuarios;
    }

    public void setBtnUsuarios(JButton btnUsuarios) {
        this.btnUsuarios = btnUsuarios;
    }

    public JButton getBtnVolverAtras() {
        return btnVolverAtras;
    }

    public void setBtnVolverAtras(JButton btnVolverAtras) {
        this.btnVolverAtras = btnVolverAtras;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearObra;
    private javax.swing.JButton btnEliminarObra;
    private javax.swing.JButton btnFunciones;
    private javax.swing.JButton btnModificarObra;
    private javax.swing.JButton btnObras;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVolverAtras;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
