package vista;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JTextField;

public class VistaCrearObra extends javax.swing.JFrame {

    public VistaCrearObra() {
        initComponents();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/iconoApp.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCrearObra = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        entradaGenero = new javax.swing.JTextField();
        btnVolverAtras = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtError = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        entradaResumen = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        entradaPrimerActor = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        entradaPrecio = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        entradaNombre = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        entradaSegundoActor = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        entradaMinutos = new javax.swing.JComboBox<>();
        entradaHoras = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Obra");
        setIconImage(getIconImage());
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(28, 12, 91));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CREAR OBRA");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 700, 90));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrearObra.setBackground(new java.awt.Color(0, 124, 186));
        btnCrearObra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCrearObra.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearObra.setText("Crear obra");
        btnCrearObra.setBorderPainted(false);
        btnCrearObra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearObra.setFocusPainted(false);
        btnCrearObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearObraActionPerformed(evt);
            }
        });
        jPanel3.add(btnCrearObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 170, 50));

        jPanel4.setBackground(new java.awt.Color(205, 205, 205));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entradaGenero.setBackground(new java.awt.Color(205, 205, 205));
        entradaGenero.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entradaGenero.setForeground(new java.awt.Color(0, 124, 186));
        entradaGenero.setBorder(null);
        jPanel4.add(entradaGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 510, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 530, 30));

        btnVolverAtras.setBackground(new java.awt.Color(255, 255, 255));
        btnVolverAtras.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVolverAtras.setForeground(new java.awt.Color(0, 124, 186));
        btnVolverAtras.setText("Volver atrás");
        btnVolverAtras.setBorderPainted(false);
        btnVolverAtras.setContentAreaFilled(false);
        btnVolverAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolverAtras.setFocusPainted(false);
        jPanel3.add(btnVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 120, 30));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 124, 186));
        jLabel11.setText("Precio del boleto:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 30));

        txtError.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtError.setForeground(new java.awt.Color(255, 0, 51));
        txtError.setText("Error");
        jPanel3.add(txtError, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 124, 186));
        jLabel12.setText("Nombre de obra:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 18, 150, 30));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 124, 186));
        jLabel13.setText("Género:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 30));

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 124, 186));
        jLabel14.setText("Resumen:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 40));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 124, 186));
        jLabel15.setText("Minutos:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, 30));

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 124, 186));
        jLabel16.setText("Primer actor:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 30));

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 124, 186));
        jLabel17.setText("Segundo actor:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));

        jPanel5.setBackground(new java.awt.Color(205, 205, 205));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entradaResumen.setBackground(new java.awt.Color(205, 205, 205));
        entradaResumen.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entradaResumen.setForeground(new java.awt.Color(0, 124, 186));
        entradaResumen.setBorder(null);
        jPanel5.add(entradaResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 510, 50));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 530, 50));

        jPanel7.setBackground(new java.awt.Color(205, 205, 205));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entradaPrimerActor.setBackground(new java.awt.Color(205, 205, 205));
        entradaPrimerActor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entradaPrimerActor.setForeground(new java.awt.Color(0, 124, 186));
        entradaPrimerActor.setBorder(null);
        jPanel7.add(entradaPrimerActor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 510, 30));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 530, 30));

        jPanel8.setBackground(new java.awt.Color(205, 205, 205));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entradaPrecio.setBackground(new java.awt.Color(205, 205, 205));
        entradaPrecio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entradaPrecio.setForeground(new java.awt.Color(0, 124, 186));
        entradaPrecio.setBorder(null);
        jPanel8.add(entradaPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 510, 30));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 530, 30));

        jPanel9.setBackground(new java.awt.Color(205, 205, 205));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entradaNombre.setBackground(new java.awt.Color(205, 205, 205));
        entradaNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entradaNombre.setForeground(new java.awt.Color(0, 124, 186));
        entradaNombre.setBorder(null);
        jPanel9.add(entradaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 510, 30));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 530, 30));

        jPanel10.setBackground(new java.awt.Color(205, 205, 205));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entradaSegundoActor.setBackground(new java.awt.Color(205, 205, 205));
        entradaSegundoActor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entradaSegundoActor.setForeground(new java.awt.Color(0, 124, 186));
        entradaSegundoActor.setBorder(null);
        jPanel10.add(entradaSegundoActor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 510, 30));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 530, 30));

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 124, 186));
        jLabel18.setText("Duración");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 30));

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 124, 186));
        jLabel19.setText("Horas:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, 30));

        entradaMinutos.setBackground(new java.awt.Color(205, 205, 205));
        entradaMinutos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entradaMinutos.setForeground(new java.awt.Color(0, 124, 186));
        entradaMinutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        jPanel3.add(entradaMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 110, 30));

        entradaHoras.setBackground(new java.awt.Color(205, 205, 205));
        entradaHoras.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entradaHoras.setForeground(new java.awt.Color(0, 124, 186));
        entradaHoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel3.add(entradaHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 110, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 91, 700, 430));

        jPanel11.setBackground(new java.awt.Color(205, 205, 205));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearObraActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCrearObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCrearObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCrearObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCrearObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCrearObra().setVisible(true);
            }
        });
    }

    public JButton getBtnCrearObra() {
        return btnCrearObra;
    }

    public JButton getBtnVolverAtras() {
        return btnVolverAtras;
    }

    public JComboBox<String> getEntradaHoras() {
        return entradaHoras;
    }

    public JComboBox<String> getEntradaMinutos() {
        return entradaMinutos;
    }
    
    public JTextField getEntradaPrecio() {
        return entradaPrecio;
    }

    public JTextField getEntradaPrimerActor() {
        return entradaPrimerActor;
    }

    public JTextField getEntradaResumen() {
        return entradaResumen;
    }

    public JTextField getEntradaSegundoActor() {
        return entradaSegundoActor;
    }

    public JTextField getEntradaNombre() {
        return entradaNombre;
    }

    public JLabel getTxtError() {
        return txtError;
    }

    public void setTxtError(JLabel txtError) {
        this.txtError = txtError;
    }

    public JTextField getEntradaGenero() {
        return entradaGenero;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearObra;
    private javax.swing.JButton btnVolverAtras;
    private javax.swing.JTextField entradaGenero;
    private javax.swing.JComboBox<String> entradaHoras;
    private javax.swing.JComboBox<String> entradaMinutos;
    private javax.swing.JTextField entradaNombre;
    private javax.swing.JTextField entradaPrecio;
    private javax.swing.JTextField entradaPrimerActor;
    private javax.swing.JTextField entradaResumen;
    private javax.swing.JTextField entradaSegundoActor;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel txtError;
    // End of variables declaration//GEN-END:variables
}
