package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;

public class VistaComponenteObraUsuario extends javax.swing.JPanel {

    /**
     * Creates new form VistaComponenteUsuario
     */
    public VistaComponenteObraUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resumen = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        duracion = new javax.swing.JLabel();
        nombreObra = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        genero = new javax.swing.JLabel();
        btnVerFunciones = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resumen.setEditable(false);
        resumen.setBackground(new java.awt.Color(255, 255, 255));
        resumen.setColumns(20);
        resumen.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        resumen.setForeground(new java.awt.Color(0, 124, 186));
        resumen.setRows(5);
        resumen.setBorder(null);
        jScrollPane1.setViewportView(resumen);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 420, 90));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 124, 186));
        jLabel2.setText("Resumen:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 124, 186));
        jLabel4.setText("Duración:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        duracion.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        duracion.setForeground(new java.awt.Color(0, 124, 186));
        duracion.setText("0 horas y 0 minutos");
        jPanel1.add(duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        nombreObra.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        nombreObra.setForeground(new java.awt.Color(0, 124, 186));
        nombreObra.setText("nombre obra");
        jPanel1.add(nombreObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 124, 186));
        jLabel5.setText("Obra: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 124, 186));
        jLabel3.setText("Genero:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        genero.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        genero.setForeground(new java.awt.Color(0, 124, 186));
        genero.setText("genero");
        jPanel1.add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        btnVerFunciones.setBackground(new java.awt.Color(0, 124, 186));
        btnVerFunciones.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnVerFunciones.setForeground(new java.awt.Color(255, 255, 255));
        btnVerFunciones.setText("Ver funciones");
        btnVerFunciones.setToolTipText("");
        btnVerFunciones.setBorderPainted(false);
        btnVerFunciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerFunciones.setFocusPainted(false);
        btnVerFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerFuncionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 160, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 250));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerFuncionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerFuncionesActionPerformed

    public JButton getBtnVerFunciones() {
        return btnVerFunciones;
    }

    public void setBtnVerFunciones(JButton btnVerFunciones) {
        this.btnVerFunciones = btnVerFunciones;
    }

    public JLabel getDuracion() {
        return duracion;
    }

    public void setDuracion(JLabel duracion) {
        this.duracion = duracion;
    }

    public JLabel getGenero() {
        return genero;
    }

    public void setGenero(JLabel genero) {
        this.genero = genero;
    }

    public JLabel getNombreObra() {
        return nombreObra;
    }

    public void setNombreObra(JLabel nombreObra) {
        this.nombreObra = nombreObra;
    }

    public JTextArea getResumen() {
        return resumen;
    }

    public void setResumen(JTextArea resumen) {
        this.resumen = resumen;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerFunciones;
    private javax.swing.JLabel duracion;
    private javax.swing.JLabel genero;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreObra;
    private javax.swing.JTextArea resumen;
    // End of variables declaration//GEN-END:variables
}