/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author danie
 */
public class VistaFuncionesUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form VistaUsuarios
     */
    public VistaFuncionesUsuarios() {
        initComponents();
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/iconoApp.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollPanelUsuarios = new javax.swing.JScrollPane();
        panelFunciones = new javax.swing.JPanel();
        btnVolverAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        entradaBusqueda = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        nombreObra = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Funciones");
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPanelUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        scrollPanelUsuarios.setBorder(null);

        panelFunciones.setBackground(new java.awt.Color(255, 255, 255));
        panelFunciones.setLayout(new java.awt.GridBagLayout());
        scrollPanelUsuarios.setViewportView(panelFunciones);

        jPanel1.add(scrollPanelUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 620, 330));

        btnVolverAtras.setBackground(new java.awt.Color(255, 255, 255));
        btnVolverAtras.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVolverAtras.setForeground(new java.awt.Color(0, 124, 186));
        btnVolverAtras.setText("Volver atrás");
        btnVolverAtras.setBorderPainted(false);
        btnVolverAtras.setContentAreaFilled(false);
        btnVolverAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolverAtras.setFocusPainted(false);
        btnVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 150, 30));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 124, 186));
        jLabel1.setText("Buscar:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        jPanel4.setBackground(new java.awt.Color(205, 205, 205));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entradaBusqueda.setBackground(new java.awt.Color(205, 205, 205));
        entradaBusqueda.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entradaBusqueda.setForeground(new java.awt.Color(0, 124, 186));
        entradaBusqueda.setBorder(null);
        entradaBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                entradaBusquedaKeyReleased(evt);
            }
        });
        jPanel4.add(entradaBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 330, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 700, 420));

        jPanel2.setBackground(new java.awt.Color(28, 12, 91));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreObra.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        nombreObra.setForeground(new java.awt.Color(255, 255, 255));
        nombreObra.setText("Nombre obra");
        jPanel2.add(nombreObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, 40));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("LISTA DE FUNCIONES");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverAtrasActionPerformed

    private void entradaBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entradaBusquedaKeyReleased

    }//GEN-LAST:event_entradaBusquedaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaFuncionesUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaFuncionesUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaFuncionesUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaFuncionesUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaFuncionesUsuarios().setVisible(true);
            }
        });
    }

    public JButton getBtnVolverAtras() {
        return btnVolverAtras;
    }

    public void setBtnVolverAtras(JButton btnVolverAtras) {
        this.btnVolverAtras = btnVolverAtras;
    }

    public JTextField getEntradaBusqueda() {
        return entradaBusqueda;
    }

    public void setEntradaBusqueda(JTextField entradaBusqueda) {
        this.entradaBusqueda = entradaBusqueda;
    }

    public JLabel getNombreObra() {
        return nombreObra;
    }

    public void setNombreObra(JLabel nombreObra) {
        this.nombreObra = nombreObra;
    }

    public JPanel getPanelFunciones() {
        return panelFunciones;
    }

    public void setPanelFunciones(JPanel panelFunciones) {
        this.panelFunciones = panelFunciones;
    }

    public JScrollPane getScrollPanelUsuarios() {
        return scrollPanelUsuarios;
    }

    public void setScrollPanelUsuarios(JScrollPane scrollPanelUsuarios) {
        this.scrollPanelUsuarios = scrollPanelUsuarios;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolverAtras;
    private javax.swing.JTextField entradaBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel nombreObra;
    private javax.swing.JPanel panelFunciones;
    private javax.swing.JScrollPane scrollPanelUsuarios;
    // End of variables declaration//GEN-END:variables
}
