package vista;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;

public class VistaModificarObra extends javax.swing.JFrame {

    /**
     * Creates new form ModificarObra
     */
    public VistaModificarObra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        entradaNombre = new javax.swing.JTextField();
        entradaResumen = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        entradaDuracion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        entradaGenero = new javax.swing.JTextField();
        entradaPrecioBoleto = new javax.swing.JTextField();
        entradaSegundoActor = new javax.swing.JTextField();
        entradaPrimerActor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 623));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(28, 12, 91));
        jPanel1.setToolTipText("");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 124, 186));
        btnVolver.setText("Volver atrás");
        btnVolver.setBorderPainted(false);
        btnVolver.setFocusPainted(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel3.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 120, 30));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 124, 186));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Llena los siguientes datos para modificar un Obra");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 670, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 124, 186));
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 124, 186));
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 124, 186));
        jLabel11.setText("Nombre:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        entradaNombre.setBackground(new java.awt.Color(205, 205, 205));
        entradaNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entradaNombre.setForeground(new java.awt.Color(0, 124, 186));
        entradaNombre.setBorder(null);
        jPanel3.add(entradaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 460, 30));

        entradaResumen.setBackground(new java.awt.Color(205, 205, 205));
        entradaResumen.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entradaResumen.setForeground(new java.awt.Color(0, 124, 186));
        entradaResumen.setBorder(null);
        jPanel3.add(entradaResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 370, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 124, 186));
        jLabel13.setText("Género:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 124, 186));
        jLabel14.setText("Resumen Temático:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 124, 186));
        jLabel12.setText("Duración:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        entradaDuracion.setBackground(new java.awt.Color(205, 205, 205));
        entradaDuracion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entradaDuracion.setForeground(new java.awt.Color(0, 124, 186));
        entradaDuracion.setBorder(null);
        jPanel3.add(entradaDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 450, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 124, 186));
        jLabel15.setText("Primer actor principal:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        btnModificar.setBackground(new java.awt.Color(0, 124, 186));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.setBorderPainted(false);
        btnModificar.setFocusPainted(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel3.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 150, 57));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 124, 186));
        jLabel17.setText("Precio del boleto:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 124, 186));
        jLabel18.setText("Segundo actor principal:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        entradaGenero.setBackground(new java.awt.Color(205, 205, 205));
        entradaGenero.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entradaGenero.setForeground(new java.awt.Color(0, 124, 186));
        entradaGenero.setBorder(null);
        jPanel3.add(entradaGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 470, 30));

        entradaPrecioBoleto.setBackground(new java.awt.Color(205, 205, 205));
        entradaPrecioBoleto.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entradaPrecioBoleto.setForeground(new java.awt.Color(0, 124, 186));
        entradaPrecioBoleto.setBorder(null);
        jPanel3.add(entradaPrecioBoleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 380, 30));

        entradaSegundoActor.setBackground(new java.awt.Color(205, 205, 205));
        entradaSegundoActor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entradaSegundoActor.setForeground(new java.awt.Color(0, 124, 186));
        entradaSegundoActor.setBorder(null);
        jPanel3.add(entradaSegundoActor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 330, 30));

        entradaPrimerActor.setBackground(new java.awt.Color(205, 205, 205));
        entradaPrimerActor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entradaPrimerActor.setForeground(new java.awt.Color(0, 124, 186));
        entradaPrimerActor.setBorder(null);
        jPanel3.add(entradaPrimerActor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 350, 30));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Modificar Obra");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel6)
                .addContainerGap(199, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaModificarObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaModificarObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaModificarObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaModificarObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaModificarObra().setVisible(true);
            }
        });
    }

    public JButton getBtnModificar() {
        return btnModificar;
    }

    public void setBtnModificar(JButton btnModificar) {
        this.btnModificar = btnModificar;
    }

    public JButton getBtnVolver() {
        return btnVolver;
    }

    public void setBtnVolver(JButton btnVolver) {
        this.btnVolver = btnVolver;
    }

    public JTextField getEntradaDuracion() {
        return entradaDuracion;
    }

    public void setEntradaDuracion(JTextField entradaDuracion) {
        this.entradaDuracion = entradaDuracion;
    }

    public JTextField getEntradaGenero() {
        return entradaGenero;
    }

    public void setEntradaGenero(JTextField entradaGenero) {
        this.entradaGenero = entradaGenero;
    }

    public JTextField getEntradaNombre() {
        return entradaNombre;
    }

    public void setEntradaNombre(JTextField entradaNombre) {
        this.entradaNombre = entradaNombre;
    }

    public JTextField getEntradaPrecioBoleto() {
        return entradaPrecioBoleto;
    }

    public void setEntradaPrecioBoleto(JTextField entradaPrecioBoleto) {
        this.entradaPrecioBoleto = entradaPrecioBoleto;
    }

    public JTextField getEntradaPrimerActor() {
        return entradaPrimerActor;
    }

    public void setEntradaPrimerActor(JTextField entradaPrimerActor) {
        this.entradaPrimerActor = entradaPrimerActor;
    }

    public JTextField getEntradaResumen() {
        return entradaResumen;
    }

    public void setEntradaResumen(JTextField entradaResumen) {
        this.entradaResumen = entradaResumen;
    }

    public JTextField getEntradaSegundoActor() {
        return entradaSegundoActor;
    }

    public void setEntradaSegundoActor(JTextField entradaSegundoActor) {
        this.entradaSegundoActor = entradaSegundoActor;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JTextField entradaDuracion;
    private javax.swing.JTextField entradaGenero;
    private javax.swing.JTextField entradaNombre;
    private javax.swing.JTextField entradaPrecioBoleto;
    private javax.swing.JTextField entradaPrimerActor;
    private javax.swing.JTextField entradaResumen;
    private javax.swing.JTextField entradaSegundoActor;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
