/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author danie
 */
public class VistaObras extends javax.swing.JFrame {

    /**
     * Creates new form VistaUsuarios
     */
    public VistaObras() {
        initComponents();
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/iconoApp.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollPanelUsuarios = new javax.swing.JScrollPane();
        panelObras = new javax.swing.JPanel();
        btnVolverAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        entradaBusqueda = new javax.swing.JTextField();
        btnCrearObra = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnObras = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Obras");
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPanelUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        scrollPanelUsuarios.setBorder(null);

        panelObras.setBackground(new java.awt.Color(255, 255, 255));
        panelObras.setLayout(new java.awt.GridBagLayout());
        scrollPanelUsuarios.setViewportView(panelObras);

        jPanel1.add(scrollPanelUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 620, 330));

        btnVolverAtras.setBackground(new java.awt.Color(255, 255, 255));
        btnVolverAtras.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVolverAtras.setForeground(new java.awt.Color(0, 124, 186));
        btnVolverAtras.setText("Volver atrás");
        btnVolverAtras.setBorderPainted(false);
        btnVolverAtras.setContentAreaFilled(false);
        btnVolverAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolverAtras.setFocusPainted(false);
        btnVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 150, 30));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 124, 186));
        jLabel1.setText("Buscar:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        jPanel4.setBackground(new java.awt.Color(205, 205, 205));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entradaBusqueda.setBackground(new java.awt.Color(205, 205, 205));
        entradaBusqueda.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entradaBusqueda.setForeground(new java.awt.Color(0, 124, 186));
        entradaBusqueda.setBorder(null);
        entradaBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                entradaBusquedaKeyReleased(evt);
            }
        });
        jPanel4.add(entradaBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 330, 30));

        btnCrearObra.setBackground(new java.awt.Color(0, 124, 186));
        btnCrearObra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCrearObra.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearObra.setText("Crear obra");
        btnCrearObra.setBorderPainted(false);
        btnCrearObra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearObra.setDefaultCapable(false);
        btnCrearObra.setFocusPainted(false);
        btnCrearObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearObraActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 700, 420));

        jPanel2.setBackground(new java.awt.Color(28, 12, 91));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnObras.setBackground(new java.awt.Color(28, 12, 91));
        btnObras.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnObras.setForeground(new java.awt.Color(255, 255, 255));
        btnObras.setText("Obras");
        btnObras.setBorder(null);
        btnObras.setBorderPainted(false);
        btnObras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnObras.setDefaultCapable(false);
        btnObras.setFocusPainted(false);
        jPanel2.add(btnObras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, 60));

        btnUsuarios.setBackground(new java.awt.Color(28, 12, 91));
        btnUsuarios.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setBorder(null);
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.setDefaultCapable(false);
        btnUsuarios.setFocusPainted(false);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jPanel2.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 120, 60));

        btnReporte.setBackground(new java.awt.Color(28, 12, 91));
        btnReporte.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte.setText("Reporte");
        btnReporte.setBorder(null);
        btnReporte.setBorderPainted(false);
        btnReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporte.setDefaultCapable(false);
        btnReporte.setFocusPainted(false);
        jPanel2.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 110, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverAtrasActionPerformed

    private void entradaBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entradaBusquedaKeyReleased

    }//GEN-LAST:event_entradaBusquedaKeyReleased

    private void btnCrearObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearObraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaObras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaObras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaObras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaObras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaObras().setVisible(true);
            }
        });
    }

    public JButton getBtnCrearObra() {
        return btnCrearObra;
    }

    public JButton getBtnReporte() {
        return btnReporte;
    }
    
    public JButton getBtnObras() {
        return btnObras;
    }

    public JButton getBtnVolverAtras() {
        return btnVolverAtras;
    }

    public JTextField getEntradaBusqueda() {
        return entradaBusqueda;
    }

    public JButton getBtnUsuarios() {
        return btnUsuarios;
    }

    public void setBtnUsuarios(JButton btnUsuarios) {
        this.btnUsuarios = btnUsuarios;
    }

    public JPanel getPanelObras() {
        return panelObras;
    }

    public void setPanelObras(JPanel panelObras) {
        this.panelObras = panelObras;
    }
    
    public JScrollPane getScrollPanelUsuarios() {
        return scrollPanelUsuarios;
    }

    public void setScrollPanelUsuarios(JScrollPane scrollPanelUsuarios) {
        this.scrollPanelUsuarios = scrollPanelUsuarios;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearObra;
    private javax.swing.JButton btnObras;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVolverAtras;
    private javax.swing.JTextField entradaBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel panelObras;
    private javax.swing.JScrollPane scrollPanelUsuarios;
    // End of variables declaration//GEN-END:variables
}
