/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author danie
 */
public class VistaTicket extends javax.swing.JFrame {

    /**
     * Creates new form RegistroUsuarios
     */
    public VistaTicket() {
        initComponents();
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/iconoApp.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cantidadBoletos = new javax.swing.JLabel();
        nombreTeatro = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        nombreObra = new javax.swing.JLabel();
        fechaCompra = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        asd = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        precioTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pago = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cambio = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nasd = new javax.swing.JLabel();
        numeroVenta = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fechaFuncion = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        horaFuncion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ticket de Venta");
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(400, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(28, 12, 91));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TICKET DE VENTA");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 230, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 80));

        cantidadBoletos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cantidadBoletos.setForeground(new java.awt.Color(0, 124, 186));
        cantidadBoletos.setText("No.");
        jPanel1.add(cantidadBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 140, -1));

        nombreTeatro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreTeatro.setForeground(new java.awt.Color(0, 124, 186));
        nombreTeatro.setText("Nombre teatro");
        jPanel1.add(nombreTeatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        nombreTeatro.getAccessibleContext().setAccessibleDescription("Nombre de Usuario");

        usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usuario.setForeground(new java.awt.Color(0, 124, 186));
        usuario.setText("nombre");
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 20));

        nombreObra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreObra.setForeground(new java.awt.Color(0, 124, 186));
        nombreObra.setText("nombre obra");
        jPanel1.add(nombreObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        fechaCompra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fechaCompra.setForeground(new java.awt.Color(0, 124, 186));
        fechaCompra.setText("dddd/mm/aa");
        jPanel1.add(fechaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        btnFinalizar.setBackground(new java.awt.Color(255, 255, 255));
        btnFinalizar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(0, 124, 186));
        btnFinalizar.setText("Finalizar");
        btnFinalizar.setBorderPainted(false);
        btnFinalizar.setContentAreaFilled(false);
        btnFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinalizar.setFocusPainted(false);
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 100, 30));

        asd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        asd.setForeground(new java.awt.Color(0, 124, 186));
        asd.setText("Usuario:");
        jPanel1.add(asd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 124, 186));
        jLabel8.setText("Obra:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 124, 186));
        jLabel9.setText("Fecha de compra:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        precioTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        precioTotal.setForeground(new java.awt.Color(0, 124, 186));
        precioTotal.setText("$$$");
        jPanel1.add(precioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 70, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 124, 186));
        jLabel4.setText("Cantidad de boletos:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 140, -1));

        pago.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pago.setForeground(new java.awt.Color(0, 124, 186));
        pago.setText("$$$");
        jPanel1.add(pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 70, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 124, 186));
        jLabel6.setText("Precio total:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 90, -1));

        cambio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cambio.setForeground(new java.awt.Color(0, 124, 186));
        cambio.setText("$$$");
        jPanel1.add(cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 60, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 124, 186));
        jLabel12.setText("Monto entregado:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 120, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 124, 186));
        jLabel13.setText("Cambio:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 60, -1));

        nasd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nasd.setForeground(new java.awt.Color(0, 124, 186));
        nasd.setText("Número de venta:");
        jPanel1.add(nasd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        numeroVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numeroVenta.setForeground(new java.awt.Color(0, 124, 186));
        numeroVenta.setText("No.");
        jPanel1.add(numeroVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 124, 186));
        jLabel11.setText("Fecha función:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        fechaFuncion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fechaFuncion.setForeground(new java.awt.Color(0, 124, 186));
        fechaFuncion.setText("dddd/mm/aa");
        jPanel1.add(fechaFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 124, 186));
        jLabel14.setText("Hora función:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        horaFuncion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        horaFuncion.setForeground(new java.awt.Color(0, 124, 186));
        horaFuncion.setText("00:00");
        jPanel1.add(horaFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaTicket().setVisible(true);
            }
        });
    }

    public JButton getBtnFinalizar() {
        return btnFinalizar;
    }

    public void setBtnFinalizar(JButton btnFinalizar) {
        this.btnFinalizar = btnFinalizar;
    }

    public JLabel getCambio() {
        return cambio;
    }

    public void setCambio(JLabel cambio) {
        this.cambio = cambio;
    }

    public JLabel getCantidadBoletos() {
        return cantidadBoletos;
    }

    public void setCantidadBoletos(JLabel cantidadBoletos) {
        this.cantidadBoletos = cantidadBoletos;
    }

    public JLabel getFechaCompra() {
        return fechaCompra;
    }

    public void setFechaCompra(JLabel fechaCompra) {
        this.fechaCompra = fechaCompra;
    }

    public JLabel getFechaFuncion() {
        return fechaFuncion;
    }

    public void setFechaFuncion(JLabel fechaFuncion) {
        this.fechaFuncion = fechaFuncion;
    }

    public JLabel getHoraFuncion() {
        return horaFuncion;
    }

    public void setHoraFuncion(JLabel horaFuncion) {
        this.horaFuncion = horaFuncion;
    }

    public JLabel getNombreObra() {
        return nombreObra;
    }

    public void setNombreObra(JLabel nombreObra) {
        this.nombreObra = nombreObra;
    }

    public JLabel getNombreTeatro() {
        return nombreTeatro;
    }

    public void setNombreTeatro(JLabel nombreTeatro) {
        this.nombreTeatro = nombreTeatro;
    }

    public JLabel getNumeroVenta() {
        return numeroVenta;
    }

    public void setNumeroVenta(JLabel numeroVenta) {
        this.numeroVenta = numeroVenta;
    }

    public JLabel getPago() {
        return pago;
    }

    public void setPago(JLabel pago) {
        this.pago = pago;
    }

    public JLabel getPrecioTotal() {
        return precioTotal;
    }

    public void setPrecioTotal(JLabel precioTotal) {
        this.precioTotal = precioTotal;
    }

    public JLabel getUsuario() {
        return usuario;
    }

    public void setUsuario(JLabel usuario) {
        this.usuario = usuario;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asd;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel cambio;
    private javax.swing.JLabel cantidadBoletos;
    private javax.swing.JLabel fechaCompra;
    private javax.swing.JLabel fechaFuncion;
    private javax.swing.JLabel horaFuncion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nasd;
    private javax.swing.JLabel nombreObra;
    private javax.swing.JLabel nombreTeatro;
    private javax.swing.JLabel numeroVenta;
    private javax.swing.JLabel pago;
    private javax.swing.JLabel precioTotal;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
