/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author danie
 */
public class VistaComponenteFuncionUsuario extends javax.swing.JPanel {

    /**
     * Creates new form VistaComponenteUsuario
     */
    public VistaComponenteFuncionUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hora1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        hora = new javax.swing.JLabel();
        btnReservar = new javax.swing.JButton();
        fecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        hora1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        hora1.setForeground(new java.awt.Color(0, 0, 0));
        hora1.setText("00:00");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hora.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        hora.setForeground(new java.awt.Color(0, 124, 186));
        hora.setText("00:00");
        jPanel1.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        btnReservar.setBackground(new java.awt.Color(0, 124, 186));
        btnReservar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnReservar.setForeground(new java.awt.Color(255, 255, 255));
        btnReservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoModificar.png"))); // NOI18N
        btnReservar.setText("Reservar");
        btnReservar.setToolTipText("Modificar función");
        btnReservar.setBorderPainted(false);
        btnReservar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReservar.setFocusPainted(false);
        btnReservar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/password.png"))); // NOI18N
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });
        jPanel1.add(btnReservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 140, 50));

        fecha.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        fecha.setForeground(new java.awt.Color(0, 124, 186));
        fecha.setText("aaaa/mm/dd");
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 124, 186));
        jLabel1.setText("Horario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 124, 186));
        jLabel2.setText("Fecha:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservarActionPerformed

    public JButton getBtnReservar() {
        return btnReservar;
    }

    public void setBtnReservar(JButton btnReservar) {
        this.btnReservar = btnReservar;
    }
    
    public JLabel getFecha() {
        return fecha;
    }

    public void setFecha(JLabel fecha) {
        this.fecha = fecha;
    }

    public JLabel getHora() {
        return hora;
    }

    public void setHora(JLabel hora) {
        this.hora = hora;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReservar;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel hora1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}