package vista;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author danie
 */
public class VistaReservar extends javax.swing.JFrame {

    /**
     * Creates new form MenuUsuario
     */
    public VistaReservar() {
        initComponents();
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/iconoApp.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        precioBoletosA = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nombreObra = new javax.swing.JLabel();
        btnReservarBoletos = new javax.swing.JButton();
        btnVolverAtras = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        precioBoletosB = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        precioBoletosC = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        precioTotal = new javax.swing.JLabel();
        precioBoletosD = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cantidadBoletos = new javax.swing.JLabel();
        panelAsientosB = new javax.swing.JPanel();
        panelAsientosC = new javax.swing.JPanel();
        panelAsientosD = new javax.swing.JPanel();
        panelAsientosA = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reservar Asientos");
        setIconImage(getIconImage());
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(28, 12, 91));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("RESERVAR");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 80));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 124, 186));
        jLabel1.setText("Asientos:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 120, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 124, 186));
        jLabel3.setText("Obra:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 3, 60, 30));

        precioBoletosA.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        precioBoletosA.setForeground(new java.awt.Color(102, 102, 102));
        precioBoletosA.setText("$0000");
        jPanel3.add(precioBoletosA, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, 30));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 124, 186));
        jLabel10.setText("A:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 30, 30));

        nombreObra.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        nombreObra.setForeground(new java.awt.Color(0, 124, 186));
        nombreObra.setText("Nombre Obra");
        jPanel3.add(nombreObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 190, 20));

        btnReservarBoletos.setBackground(new java.awt.Color(0, 124, 186));
        btnReservarBoletos.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnReservarBoletos.setForeground(new java.awt.Color(255, 255, 255));
        btnReservarBoletos.setText("Comprar boletos");
        btnReservarBoletos.setBorderPainted(false);
        btnReservarBoletos.setFocusPainted(false);
        btnReservarBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarBoletosActionPerformed(evt);
            }
        });
        jPanel3.add(btnReservarBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 210, 40));

        btnVolverAtras.setBackground(new java.awt.Color(255, 255, 255));
        btnVolverAtras.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnVolverAtras.setForeground(new java.awt.Color(0, 124, 186));
        btnVolverAtras.setText("Volver atrás");
        btnVolverAtras.setBorderPainted(false);
        btnVolverAtras.setContentAreaFilled(false);
        btnVolverAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolverAtras.setFocusPainted(false);
        jPanel3.add(btnVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 150, 30));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 124, 186));
        jLabel12.setText("B:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 30, 30));

        precioBoletosB.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        precioBoletosB.setForeground(new java.awt.Color(102, 102, 102));
        precioBoletosB.setText("$0000");
        jPanel3.add(precioBoletosB, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, 30));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 124, 186));
        jLabel14.setText("C:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 30, 30));

        precioBoletosC.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        precioBoletosC.setForeground(new java.awt.Color(102, 102, 102));
        precioBoletosC.setText("$0000");
        jPanel3.add(precioBoletosC, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, 30));

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 124, 186));
        jLabel16.setText("D:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 30, 30));

        precioTotal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        precioTotal.setForeground(new java.awt.Color(102, 102, 102));
        precioTotal.setText("Precio Total");
        jPanel3.add(precioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 30));

        precioBoletosD.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        precioBoletosD.setForeground(new java.awt.Color(102, 102, 102));
        precioBoletosD.setText("$0000");
        jPanel3.add(precioBoletosD, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, 30));

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 124, 186));
        jLabel19.setText("Boletos:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 90, -1));

        cantidadBoletos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cantidadBoletos.setForeground(new java.awt.Color(102, 102, 102));
        cantidadBoletos.setText("Boletos");
        jPanel3.add(cantidadBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 30));

        panelAsientosB.setBackground(new java.awt.Color(204, 204, 204));
        panelAsientosB.setPreferredSize(new java.awt.Dimension(150, 130));

        javax.swing.GroupLayout panelAsientosBLayout = new javax.swing.GroupLayout(panelAsientosB);
        panelAsientosB.setLayout(panelAsientosBLayout);
        panelAsientosBLayout.setHorizontalGroup(
            panelAsientosBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        panelAsientosBLayout.setVerticalGroup(
            panelAsientosBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel3.add(panelAsientosB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 130));

        panelAsientosC.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelAsientosCLayout = new javax.swing.GroupLayout(panelAsientosC);
        panelAsientosC.setLayout(panelAsientosCLayout);
        panelAsientosCLayout.setHorizontalGroup(
            panelAsientosCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        panelAsientosCLayout.setVerticalGroup(
            panelAsientosCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel3.add(panelAsientosC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 360, 130));

        panelAsientosD.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelAsientosDLayout = new javax.swing.GroupLayout(panelAsientosD);
        panelAsientosD.setLayout(panelAsientosDLayout);
        panelAsientosDLayout.setHorizontalGroup(
            panelAsientosDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        panelAsientosDLayout.setVerticalGroup(
            panelAsientosDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel3.add(panelAsientosD, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 150, 130));

        panelAsientosA.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelAsientosALayout = new javax.swing.GroupLayout(panelAsientosA);
        panelAsientosA.setLayout(panelAsientosALayout);
        panelAsientosALayout.setHorizontalGroup(
            panelAsientosALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        panelAsientosALayout.setVerticalGroup(
            panelAsientosALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel3.add(panelAsientosA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 360, 130));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 124, 186));
        jLabel4.setText("Precio total:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 130, -1));

        textError.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textError.setForeground(new java.awt.Color(255, 0, 0));
        textError.setText("Error");
        jPanel3.add(textError, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 700, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservarBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarBoletosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservarBoletosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaReservar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaReservar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaReservar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaReservar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaReservar().setVisible(true);
            }
        });
    }

    public JLabel getTextError() {
        return textError;
    }

    public void setTextError(JLabel textError) {
        this.textError = textError;
    }
    
    public JLabel getNombreObra() {
        return nombreObra;
    }

    public void setNombreObra(JLabel nombreObra) {
        this.nombreObra = nombreObra;
    }
    
    public JButton getBtnVolverAtras() {
        return btnVolverAtras;
    }

    public void setBtnVolverAtras(JButton btnVolverAtras) {
        this.btnVolverAtras = btnVolverAtras;
    }
    
    public JButton getBtnReservarBoletos() {
        return btnReservarBoletos;
    }

    public void setBtnReservarBoletos(JButton btnReservarBoletos) {
        this.btnReservarBoletos = btnReservarBoletos;
    }

    public JLabel getCantidadBoletos() {
        return cantidadBoletos;
    }

    public void setCantidadBoletos(JLabel cantidadBoletos) {
        this.cantidadBoletos = cantidadBoletos;
    }

    public JPanel getPanelAsientosA() {
        return panelAsientosA;
    }

    public void setPanelAsientosA(JPanel panelAsientosA) {
        this.panelAsientosA = panelAsientosA;
    }

    public JPanel getPanelAsientosB() {
        return panelAsientosB;
    }

    public void setPanelAsientosB(JPanel panelAsientosB) {
        this.panelAsientosB = panelAsientosB;
    }

    public JPanel getPanelAsientosC() {
        return panelAsientosC;
    }

    public void setPanelAsientosC(JPanel panelAsientosC) {
        this.panelAsientosC = panelAsientosC;
    }

    public JPanel getPanelAsientosD() {
        return panelAsientosD;
    }

    public void setPanelAsientosD(JPanel panelAsientosD) {
        this.panelAsientosD = panelAsientosD;
    }

    public JLabel getPrecioBoletosA() {
        return precioBoletosA;
    }

    public void setPrecioBoletosA(JLabel precioBoletosA) {
        this.precioBoletosA = precioBoletosA;
    }

    public JLabel getPrecioBoletosB() {
        return precioBoletosB;
    }

    public void setPrecioBoletosB(JLabel precioBoletosB) {
        this.precioBoletosB = precioBoletosB;
    }

    public JLabel getPrecioBoletosC() {
        return precioBoletosC;
    }

    public void setPrecioBoletosC(JLabel precioBoletosC) {
        this.precioBoletosC = precioBoletosC;
    }

    public JLabel getPrecioBoletosD() {
        return precioBoletosD;
    }

    public void setPrecioBoletosD(JLabel precioBoletosD) {
        this.precioBoletosD = precioBoletosD;
    }

    public JLabel getPrecioTotal() {
        return precioTotal;
    }

    public void setPrecioTotal(JLabel precioTotal) {
        this.precioTotal = precioTotal;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReservarBoletos;
    private javax.swing.JButton btnVolverAtras;
    private javax.swing.JLabel cantidadBoletos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nombreObra;
    private javax.swing.JPanel panelAsientosA;
    private javax.swing.JPanel panelAsientosB;
    private javax.swing.JPanel panelAsientosC;
    private javax.swing.JPanel panelAsientosD;
    private javax.swing.JLabel precioBoletosA;
    private javax.swing.JLabel precioBoletosB;
    private javax.swing.JLabel precioBoletosC;
    private javax.swing.JLabel precioBoletosD;
    private javax.swing.JLabel precioTotal;
    private javax.swing.JLabel textError;
    // End of variables declaration//GEN-END:variables
}
